# -*- coding: utf-8 -*-
"""06 Github Best Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17cp4cu9zUmDrYRiEhnE2zJsYAAleU2hs
"""

import sys
import subprocess
import warnings
warnings.filterwarnings('ignore')

def ensure_package(pkg_name, import_name=None):
    """Install package if import fails."""
    import importlib
    try:
        importlib.import_module(import_name or pkg_name)
    except Exception:
        try:
            subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', pkg_name])
        except Exception as e:
            print(f'Package install skipped/failed for {pkg_name}: {e}')

for pkg, imp in [
    ('pandas', 'pandas'),
    ('numpy', 'numpy'),
    ('matplotlib', 'matplotlib'),
    ('scikit-learn', 'sklearn'),
    ('seaborn', 'seaborn'),
    ('xgboost', 'xgboost'),
    ('shap', 'shap'),
]:
    ensure_package(pkg, imp)

import os
import re
import json
import math
import textwrap
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display

try:
    from google.colab import files
    IN_COLAB = True
except Exception:
    IN_COLAB = False

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score,
    roc_curve, precision_recall_curve,
    confusion_matrix, classification_report
)
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.inspection import PartialDependenceDisplay, permutation_importance
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.base import clone
from xgboost import XGBClassifier
import shap

plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['axes.grid'] = True
sns.set_theme(style='whitegrid')
np.random.seed(42)
random.seed(42)

# UPLOADING CSV FILE
import pandas as pd
file_name = 'Foodpanda Analysis Dataset.csv'
print('\n' + '='*80)
print('STEP 2: UPLOAD CSV FILE')
print('='*80)
df = pd.read_csv(file_name)
print(f'Loaded file: {file_name}')
print(f'Dataset shape: {df.shape}')
display(df.head())

plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['axes.grid'] = True
sns.set_theme(style='whitegrid')
np.random.seed(42)
random.seed(42)

def safe_to_datetime(series):
    return pd.to_datetime(series, errors='coerce')

def cap_outliers_iqr(df_numeric, numeric_features_list):
    """Caps outliers in numeric columns using the IQR method."""
    capping_log = []
    df_capped = df_numeric.copy()
    for col in numeric_features_list:
        if pd.api.types.is_numeric_dtype(df_capped[col]):
            Q1 = df_capped[col].quantile(0.25)
            Q3 = df_capped[col].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR

            num_outliers_lower = (df_capped[col] < lower_bound).sum()
            num_outliers_upper = (df_capped[col] > upper_bound).sum()

            df_capped[col] = np.where(df_capped[col] < lower_bound, lower_bound, df_capped[col])
            df_capped[col] = np.where(df_capped[col] > upper_bound, upper_bound, df_capped[col])

            if num_outliers_lower > 0 or num_outliers_upper > 0:
                capping_log.append({
                    'variable': col,
                    'lower_bound_cap': lower_bound,
                    'upper_bound_cap': upper_bound,
                    'outliers_capped_lower': num_outliers_lower,
                    'outliers_capped_upper': num_outliers_upper
                })
    return df_capped, pd.DataFrame(capping_log)

def get_feature_names_from_preprocessor(preprocessor, numeric_features, categorical_features):
    """Extracts feature names after preprocessing."""
    feature_names = []
    cat_feature_names = []

    # Get names for numeric features (scaled)
    feature_names.extend(numeric_features)

    # Get names for one-hot encoded categorical features
    for name, transformer, features in preprocessor.transformers_:
        if name == 'cat': # Assuming 'cat' is the name given to the categorical pipeline
            onehot_encoder = transformer.named_steps['onehot']
            # This method works for scikit-learn >= 0.23
            if hasattr(onehot_encoder, 'get_feature_names_out'):
                # Get feature names from the OneHotEncoder
                encoded_feature_names = onehot_encoder.get_feature_names_out(categorical_features)
                feature_names.extend(encoded_feature_names)
                cat_feature_names.extend(encoded_feature_names)
            else:
                # Fallback for older scikit-learn versions or if get_feature_names_out is not available
                for i, col in enumerate(categorical_features):
                    for category in onehot_encoder.categories_[i]:
                        encoded_name = f'{col}_{category}'
                        feature_names.append(encoded_name)
                        cat_feature_names.append(encoded_name)
    return feature_names, cat_feature_names

#
print('STEP 3: DATA PREPROCESSING')

df_clean = df.copy()

# Drop unnamed or all-missing columns
cols_to_drop = [c for c in df_clean.columns if c.lower().startswith('unnamed') or df_clean[c].isna().all()]
if cols_to_drop:
    print(f'Dropping empty/useless columns: {cols_to_drop}')
    df_clean = df_clean.drop(columns=cols_to_drop)

# Create binary target for cancellation
if 'delivery_status' not in df_clean.columns:
    raise ValueError("The target column 'delivery_status' is missing.")

df_clean['target_cancelled'] = (df_clean['delivery_status'].astype(str).str.strip().str.lower() == 'cancelled').astype(int)
print('Target distribution (0 = not cancelled, 1 = cancelled):')
print(df_clean['target_cancelled'].value_counts())

# Parse dates safely
for dc in [c for c in df_clean.columns if 'date' in c.lower()]:
    df_clean[dc] = safe_to_datetime(df_clean[dc])

# Feature engineering from dates
if 'order_date' in df_clean.columns:
    df_clean['order_year'] = df_clean['order_date'].dt.year
    df_clean['order_month'] = df_clean['order_date'].dt.month
    df_clean['order_dayofweek'] = df_clean['order_date'].dt.dayofweek
    df_clean['order_day'] = df_clean['order_date'].dt.day
    df_clean['order_weekofyear'] = df_clean['order_date'].dt.isocalendar().week.astype('Int64')

if 'signup_date' in df_clean.columns and 'order_date' in df_clean.columns:
    df_clean['days_since_signup'] = (df_clean['order_date'] - df_clean['signup_date']).dt.days
    df_clean.loc[df_clean['days_since_signup'] < 0, 'days_since_signup'] = np.nan

if 'last_order_date' in df_clean.columns and 'order_date' in df_clean.columns:
    df_clean['days_since_last_order'] = (df_clean['order_date'] - df_clean['last_order_date']).dt.days
    df_clean.loc[df_clean['days_since_last_order'] < 0, 'days_since_last_order'] = np.nan

# Columns to exclude from modeling because they are IDs, leakage, or raw target
exclusion_cols = [
    'customer_id', 'order_id', 'delivery_status',
    'rating', 'rating_date', 'churned',
    'signup_date', 'order_date', 'last_order_date'
]
exclusion_cols = [c for c in exclusion_cols if c in df_clean.columns]
print(f'Columns excluded from modeling: {exclusion_cols}')

model_df = df_clean.drop(columns=exclusion_cols, errors='ignore').copy()

# Separate target and features
X = model_df.drop(columns=['target_cancelled'])
y = model_df['target_cancelled']

# Identify current column types
numeric_features = X.select_dtypes(include=[np.number, 'Int64']).columns.tolist()
categorical_features = [c for c in X.columns if c not in numeric_features]
print(f'Numeric features: {numeric_features}')
print(f'Categorical features: {categorical_features}')

# Cap numeric outliers before train-test split for easier reproducibility in EDA.
X_before_cap = X.copy()
X[numeric_features], capping_log = cap_outliers_iqr(X[numeric_features], numeric_features)
print('\nOutlier capping summary:')
display(capping_log)

# Split data: 50% training, 50% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.50, random_state=42, stratify=y
)
print(f'Training shape: {X_train.shape}, Testing shape: {X_test.shape}')

# Preprocessing pipelines
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())  # z-score normalization
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

# Fit preprocessing and generate encoded tables
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)
feature_names, cat_feature_names = get_feature_names_from_preprocessor(preprocessor, numeric_features, categorical_features)

X_train_processed_df = pd.DataFrame(X_train_processed, columns=feature_names, index=X_train.index)
X_test_processed_df = pd.DataFrame(X_test_processed, columns=feature_names, index=X_test.index)

print('\nProcessed training data preview:')
display(X_train_processed_df.head())

# Create One-Hot-Encoding mapping table
encoding_rows = []
for encoded_name in cat_feature_names:
    matched = False
    for original_col in categorical_features:
        prefix = original_col + '_'
        if encoded_name.startswith(prefix):
            category_value = encoded_name[len(prefix):]
            encoding_rows.append({
                'original_variable': original_col,
                'category_value': category_value,
                'encoded_column': encoded_name,
                'encoded_meaning': f"1 = {original_col} is '{category_value}', 0 = otherwise"
            })
            matched = True
            break
    if not matched:
        encoding_rows.append({
            'original_variable': 'unknown',
            'category_value': 'unknown',
            'encoded_column': encoded_name,
            'encoded_meaning': '1 indicates this encoded category is active'
        })

ohe_mapping_df = pd.DataFrame(encoding_rows)
print('\nOne-Hot-Encoding mapping table:')
display(ohe_mapping_df)

print('STEP 4: MODEL TRAINING FOR SUPERVISED CLASSIFICATION AND PREDICTION')

def plot_conf_matrix(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(title)
    plt.ylabel('Actual Label')
    plt.xlabel('Predicted Label')
    plt.show()

models = {

    'SVM': SVC(
        kernel='linear',
        probability=True,
        class_weight='balanced',
        random_state=42
    )
}

fitted_models = {}
results = []
prediction_store = {}
feature_importance_tables = {} # Initialize feature_importance_tables

for model_name, model in models.items():
    print(f'\nTraining {model_name}...')
    model.fit(X_train_processed_df, y_train)
    fitted_models[model_name] = model

    y_pred = model.predict(X_test_processed_df)
    y_proba = model.predict_proba(X_test_processed_df)[:, 1]

    correct_predictions = int((y_pred == y_test).sum())
    total_predictions = len(y_test)

    metrics_row = {
        'model': model_name,
        'accuracy': accuracy_score(y_test, y_pred),
        'roc_auc': roc_auc_score(y_test, y_proba),
        'pr_auc': average_precision_score(y_test, y_proba),
        'precision': precision_score(y_test, y_pred),
        'recall': recall_score(y_test, y_pred),
        'f1_score': f1_score(y_test, y_pred),
        'correct_predictions': correct_predictions,
        'total_predictions': total_predictions
    }
    results.append(metrics_row)
    prediction_store[model_name] = {'pred': y_pred, 'proba': y_proba}

    print(f'Correct predictions for {model_name}: {correct_predictions} out of {total_predictions}')
    print(classification_report(y_test, y_pred, digits=4))
    plot_conf_matrix(y_test, y_pred, f'Confusion Matrix - {model_name}')

results_df = pd.DataFrame(results).sort_values(by='roc_auc', ascending=False).reset_index(drop=True)
print('\nModel performance summary:')
display(results_df)

for model_name, fi_df in feature_importance_tables.items():
    top_feats = fi_df['feature'].head(min(10, len(fi_df))).tolist()
    if len(top_feats) >= 2:
        plt.figure(figsize=(9, 7))
        sns.heatmap(X_train_processed_df[top_feats].corr(), cmap='coolwarm', center=0)
        plt.title(f'Correlation Heatmap of Top Features - {model_name}')
        plt.show()

# Model-specific plots (already printed confusion matrices and feature importances)
for model_name, model in fitted_models.items():
    print(f'\nDetailed plots for {model_name}:')
    # Decision score / probability distribution
    plt.figure(figsize=(8, 4))
    plt.hist(prediction_store[model_name]['proba'], bins=30, edgecolor='black')
    plt.title(f'Predicted Cancellation Probability Distribution - {model_name}')
    plt.xlabel('Predicted Probability of Cancellation')
    plt.show()

# SHAP plots for each model using a manageable sample
background_size = min(100, len(X_train_processed_df))
explain_size = min(200, len(X_test_processed_df))
X_background = X_train_processed_df.sample(background_size, random_state=42)
X_explain = X_test_processed_df.sample(explain_size, random_state=42)

for model_name, model in fitted_models.items():
    print(f'\nSHAP explanation for {model_name}...')
    try:
        # Kernel-based approach for SVM on a small sample for reliability
        predict_fn = lambda data: model.predict_proba(pd.DataFrame(data, columns=feature_names))[:, 1]
        explainer = shap.KernelExplainer(predict_fn, X_background)
        shap_values_plot = explainer.shap_values(X_explain, nsamples=100)

        shap.summary_plot(shap_values_plot, X_explain, feature_names=feature_names, show=True)
        shap.summary_plot(shap_values_plot, X_explain, feature_names=feature_names, plot_type='bar', show=True)
    except Exception as e:
        print(f'SHAP could not be completed for {model_name}: {e}')